# Generated by Django 3.1 on 2021-02-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210209_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='syatus',
            new_name='status',
        ),
    ]
